version: '3.6'

services:
    anis:
        image: dadoum/anisette-v3-server:latest
        hostname: anis
        privileged: true
        restart: always
        volumes:
           - anisette-v3_data:~/.config/anisette-v3/lib/
        ports:
            - "7080:6969"
